---
name: 'Auto Assign'

on:
    pull_request_target:
        types: [opened, ready_for_review]

jobs:
    auto-assign-reviewers:
        runs-on: ubuntu-latest
        steps:
            - uses: kentaro-m/auto-assign-action@v1.2.2
