---
name: 'Auto Assign'

on:
    workflow_dispatch:
    pull_request:
        types: [opened, ready_for_review, unassigned]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - uses: kentaro-m/auto-assign-action@v1.2.4
