name: Codacy Code Quality Scan

on:
    workflow_dispatch:
    push:
        branches:
            - '*'

jobs:
    run-codacy-code-quality-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            # - name: Install Packages
            - run: yarn install --frozen-lockfile --immutable --immutable-cache --check-cache

            - name: Run Codacy Code Quality Scan
              uses: codacy/codacy-analysis-cli-action@master
              # with:
#

#   with:
#       output: results.sarif
#       format: sarif
#       # Adjust severity of non-security issues
#       gh-code-scanning-compat: true
#       # Force 0 exit code to allow SARIF file generation
#       # This will handover control about PR rejection to the GitHub side
#       max-allowed-issues: 2147483647

# # Upload the SARIF file generated in the previous step
# - name: Upload SARIF results file
#   uses: github/codeql-action/upload-sarif@main
#   with:
#       sarif_file: results.sarif
