---
name: Cypress E2E Test Run

on:
    workflow_dispatch:
    push:
        branches:
            - '*'

jobs:
    run-cypress-e2e-ci:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [16]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Install Packages
              uses: cypress-io/github-action@v4
              with:
                  install-command: yarn install --frozen-lockfile --immutable --immutable-cache --check-cache
                  runTests: false

            - name: Run Cypress E2E in Chrome
              uses: cypress-io/github-action@v4
              with:
                  install: false
                  build: yarn build
                  start: yarn serve
                  browser: chrome
                  parallel: true
                  record: true
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
