name: Cypress CI E2E Test Run

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Run Cypress E2E in Chrome
              uses: cypress-io/github-action@v4
              with:
                  build: npm run build
                  start: npm run serve
                  browser: chrome
                  parallel: true
                  record: true
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
