name: Jest CI Unit Test Run

on: [push]

jobs:
    jest-unit-ci-run:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn install --frozen-lockfile --immutable --immutable-cache --check-cache
            - run: yarn test --coverage

            - name: Upload test coverage to codecov.io
              uses: codecov/codecov-action@v3
              with:
                  name: codecov-audiophile-ui-umbrella
                  verbose: true
                  files: './coverage/clover.xml'
                  token: ${{ secrets.CODECOV_TOKEN }}
