---
name: Jest Unit Test Run

on:
    workflow_dispatch:
    push:
        branches:
            - '*'

jobs:
    run-jest-unit-ci:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn install --frozen-lockfile --immutable --immutable-cache --check-cache
            - run: yarn test --coverage

            - name: Upload test coverage to codecov.io
              uses: codecov/codecov-action@v3
              with:
                  name: codecov-audiophile-ui-umbrella
                  verbose: true
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Upload test coverage to codacy.com
              uses: codacy/codacy-coverage-reporter-action@v1
              with:
                  project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
                  # or
                  # api-token: ${{ secrets.CODACY_API_TOKEN }}
                  #   coverage-reports: cobertura.xml
