name: Lighthouse Audit

on:
    workflow_dispatch:
    push:
        branches:
            - '*'
            - '*/*'
            - '!main'

jobs:
    lighthouse-audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Audit app URL using Lighthouse
              uses: treosh/lighthouse-ci-action@v9
              with:
                  urls: https://audiophile-ui.vercel.app/
                  uploadArtifacts: true # save results as an action artifacts
                  temporaryPublicStorage: true # upload lighthouse report to the temporary storage
